### ISSUE TITLE
Can't create xlsx

### ISSUE THREAD

**Issue by tipok** [greenlaw110/play-excel#6]
I'm always getting this error if i'm trying to create xlsx excel document with the excel module for play

excel module 1.2.2 and play 1.2.2 are used. no jars from excel module replaced. 
template created with Excel 2010

Oops: NoClassDefFoundError
An unexpected error occured caused by exception NoClassDefFoundError: org/apache/xmlbeans/XmlOptions

play.exceptions.UnexpectedException: Unexpected Error
    at play.Invoker$Invocation.onException(Invoker.java:232)
    at play.Invoker$Invocation.run(Invoker.java:273)
    at Invocation.HTTP Request(Play!)
Caused by: java.lang.NoClassDefFoundError: org/apache/xmlbeans/XmlOptions
    at org.apache.poi.POIXMLDocumentPart.<clinit>(POIXMLDocumentPart.java:44)
    at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:62)
    at net.sf.jxls.transformer.XLSTransformer.transformXLS(XLSTransformer.java:217)
    at play.modules.excel.RenderExcel.apply(RenderExcel.java:106)
    at play.mvc.ActionInvoker.invoke(ActionInvoker.java:243)
    ... 1 more
Caused by: java.lang.ClassNotFoundException: org.apache.xmlbeans.XmlOptions
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    ... 6 more

**Comment by greenlaw110** [comment]
Use 1.2.2_x_ version to create xlsx file:
http://www.playframework.org/modules/excel-1.2.2x.zip
